### ISSUE TITLE
Django model의 ForeignKey 필드 이름 통일

### ISSUE THREAD

**Issue by pcjs156** [kookmin-sw/capstone-2023-16#14]
https://github.com/kookmin-sw/capstone-2023-16/blob/9d2723733f664c5ddfda4efba24c18e063e59a29/back/auth_app/models.py#L32

Deprecated 되기는 했지만, 위의 `EmailUser.user`와

https://github.com/kookmin-sw/capstone-2023-16/blob/9d2723733f664c5ddfda4efba24c18e063e59a29/back/auth_app/models.py#L45-L47

위의 `Post.user_id`에 각각 `_id`가 붙은게 있고 안 붙은게 있어서 헷갈릴 것 같은데, `ForeignKey` 필드 이름에는 `_id`를 붙이지 말고 필드의 `db_columns` attribute에만 명시적으로 붙여주는건 어떨까요?

호성님께서 붙여 놓으신 `@strawberry.django.type` 데코레이터로 GraphQL 타입을 선언해 놓고 클라이어언트에서 가져다 쓸 때는, 예를 들어 Post.user로 접근하지 Post.user_id로 접근하지는 않을 것 같아서요. 비슷한 맥락으로 예를 들어 `Post.category_ids` 같은 이름 보다는 `Post.categories` 같이 쓴다던지?!
뭐 여하튼,, 이왕 그렇게 쓸거,, 모델도 아예 통일해서 쓰는건 어떨까 싶군요,, 총총,,

[참고 : Django 4.1.7 'Model' document](https://django.readthedocs.io/en/stable/topics/db/models.html#:~:text=It%E2%80%99s%20suggested%2C%20but%20not%20required%2C%20that%20the%20name%20of%20a%20ForeignKey%20field%20(manufacturer%20in%20the%20example%20above)%20be%20the%20name%20of%20the%20model%2C%20lowercase.%20You%20can%20call%20the%20field%20whatever%20you%20want.%20For%20example%3A)

**Comment by sookcha** [comment]
1. 넵 말씀해주신대로 db_columns 에만 _id 가 들어가야 하는게 맞습니다
2. 모델 통일은 잘 이해하지 못했습니다!
